version: '3.8'

services: 

  postgres:
    image: postgres:15-alpine
    container_name: wether-postgres
    
    environment:
      POSTGRES_DB: wether_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
    - weather-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather_user -d weather_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  generator:
    build: ./generator
    container_name: weather-generator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: weather_db
      DB_USER: weather_user
      DB_PASSWORD: weather_pass
networks:
  weather-net:
    driver: bridge

volumes:
  postgres_data: